### YamlMime:ManagedReference
items:
- uid: Sin.Net.Domain.Config
  commentId: N:Sin.Net.Domain.Config
  id: Sin.Net.Domain.Config
  children:
  - Sin.Net.Domain.Config.ConfigBase
  langs:
  - csharp
  - vb
  name: Sin.Net.Domain.Config
  nameWithType: Sin.Net.Domain.Config
  fullName: Sin.Net.Domain.Config
  type: Namespace
  assemblies:
  - Sin.Net.Domain
references:
- uid: Sin.Net.Domain.Config.ConfigBase
  commentId: T:Sin.Net.Domain.Config.ConfigBase
  parent: Sin.Net.Domain.Config
  name: ConfigBase
  nameWithType: ConfigBase
  fullName: Sin.Net.Domain.Config.ConfigBase
- uid: Sin.Net.Domain.Config
  commentId: N:Sin.Net.Domain.Config
  name: Sin.Net.Domain.Config
  nameWithType: Sin.Net.Domain.Config
  fullName: Sin.Net.Domain.Config
